spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://161.35.231.114:3306/UsedCarSalesDemo?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/used_car_sales?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    #    password: c7c55d02-46ae-4c9d-9d56-df3c9c3cf607
    #    username: usedcarsales
    username: root
    #    password: c7c55d02-46ae-4c9d-9d56-df3c9c3cf607
    password: root
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update
      show-sql: true
  sql:
    init:
      platform: mysql
